version: '3'
services:
  opensearch-cl1-node1:
    image: week2-opensearch:latest
    container_name: opensearch-cl1-node1
    environment:
      - node.roles=master,data,transform
      - cluster.name=opensearch-cluster-1
      - node.name=opensearch-cl1-node1
      - discovery.seed_hosts=opensearch-cl1-node1,opensearch-cl1-node2,opensearch-cl1-node3
      - cluster.initial_master_nodes=opensearch-cl1-node1
      - bootstrap.memory_lock=false # AP: so memlock bootstrap check will pass - since we can't memlock unlimited on GitPod
      - node.store.allow_mmap=false # AP: so vm.max_map_count bootstrap check will pass - but don't do in prod it degrades perf
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
      - path.repo=/usr/share/opensearch/snapshots
    ports:
      - "9200:9200"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2GB
    volumes:
      - search-eng-week4-cl1-d1:/usr/share/opensearch/data
      - search-eng-week4-cl1-snapshots:/usr/share/opensearch/snapshots
    networks:
      - opensearch-net
  opensearch-cl1-node2:
    image: week2-opensearch:latest
    container_name: opensearch-cl1-node2
    environment:
      - node.roles=data
      - cluster.name=opensearch-cluster-1
      - node.name=opensearch-cl1-node2
      - discovery.seed_hosts=opensearch-cl1-node1,opensearch-cl1-node2,opensearch-cl1-node3
      - cluster.initial_master_nodes=opensearch-cl1-node1
      - bootstrap.memory_lock=false # AP: so memlock bootstrap check will pass - since we can't memlock unlimited on GitPod
      - node.store.allow_mmap=false # AP: so vm.max_map_count bootstrap check will pass - but don't do in prod it degrades perf
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
      - path.repo=/usr/share/opensearch/snapshots
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2GB
    volumes:
      - search-eng-week4-cl1-d2:/usr/share/opensearch/data
      - search-eng-week4-cl1-snapshots:/usr/share/opensearch/snapshots
    networks:
      - opensearch-net
  opensearch-cl1-node3:
    image: week2-opensearch:latest
    container_name: opensearch-cl1-node3
    environment:
      - node.roles=data
      - cluster.name=opensearch-cluster-1
      - node.name=opensearch-cl1-node3
      - discovery.seed_hosts=opensearch-cl1-node1,opensearch-cl1-node2,opensearch-cl1-node3
      - cluster.initial_master_nodes=opensearch-cl1-node1
      - bootstrap.memory_lock=false # AP: so memlock bootstrap check will pass - since we can't memlock unlimited on GitPod
      - node.store.allow_mmap=false # AP: so vm.max_map_count bootstrap check will pass - but don't do in prod it degrades perf
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
      - path.repo=/usr/share/opensearch/snapshots
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2GB
    volumes:
      - search-eng-week4-cl1-d3:/usr/share/opensearch/data
      - search-eng-week4-cl1-snapshots:/usr/share/opensearch/snapshots
    networks:
      - opensearch-net
  opensearch-cl2-node1:
    image: week2-opensearch:latest
    container_name: opensearch-cl2-node1
    environment:
      - node.roles=master,data,transform,remote_cluster_client
      - cluster.name=opensearch-cluster-2
      - node.name=opensearch-cl2-node1
      - discovery.seed_hosts=opensearch-cl2-node1,opensearch-cl2-node2,opensearch-cl2-node3
      - cluster.initial_master_nodes=opensearch-cl2-node1
      - bootstrap.memory_lock=false # AP: so memlock bootstrap check will pass - since we can't memlock unlimited on GitPod
      - node.store.allow_mmap=false # AP: so vm.max_map_count bootstrap check will pass - but don't do in prod it degrades perf
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
      - path.repo=/usr/share/opensearch/snapshots
    ports:
      - "9201:9200"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2GB
    volumes:
      - search-eng-week4-cl2-d1:/usr/share/opensearch/data
      - search-eng-week4-cl2-snapshots:/usr/share/opensearch/snapshots
    networks:
      - opensearch-net
  opensearch-cl2-node2:
    image: week2-opensearch:latest
    container_name: opensearch-cl2-node2
    environment:
      - node.roles=data,remote_cluster_client
      - cluster.name=opensearch-cluster-2
      - node.name=opensearch-cl2-node2
      - discovery.seed_hosts=opensearch-cl2-node1,opensearch-cl2-node2,opensearch-cl2-node3
      - cluster.initial_master_nodes=opensearch-cl2-node1
      - bootstrap.memory_lock=false # AP: so memlock bootstrap check will pass - since we can't memlock unlimited on GitPod
      - node.store.allow_mmap=false # AP: so vm.max_map_count bootstrap check will pass - but don't do in prod it degrades perf
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
      - path.repo=/usr/share/opensearch/snapshots
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2GB
    volumes:
      - search-eng-week4-cl2-d2:/usr/share/opensearch/data
      - search-eng-week4-cl2-snapshots:/usr/share/opensearch/snapshots
    networks:
      - opensearch-net
  opensearch-cl2-node3:
    image: week2-opensearch:latest
    container_name: opensearch-cl2-node3
    environment:
      - node.roles=data,remote_cluster_client
      - cluster.name=opensearch-cluster-2
      - node.name=opensearch-cl2-node3
      - discovery.seed_hosts=opensearch-cl2-node1,opensearch-cl2-node2,opensearch-cl2-node3
      - cluster.initial_master_nodes=opensearch-cl2-node1
      - bootstrap.memory_lock=false # AP: so memlock bootstrap check will pass - since we can't memlock unlimited on GitPod
      - node.store.allow_mmap=false # AP: so vm.max_map_count bootstrap check will pass - but don't do in prod it degrades perf
      - "OPENSEARCH_JAVA_OPTS=-Xms1G -Xmx1G"
      - path.repo=/usr/share/opensearch/snapshots
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2GB
    volumes:
      - search-eng-week4-cl2-d3:/usr/share/opensearch/data
      - search-eng-week4-cl2-snapshots:/usr/share/opensearch/snapshots
    networks:
      - opensearch-net
  opensearch-dashboards-cl1:
    image: opensearchproject/opensearch-dashboards:2.6.0
    container_name: opensearch-dashboards-cl1
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-cl1-node1:9200","https://opensearch-cl1-node2:9200","https://opensearch-cl1-node3:9200"]'
    networks:
      - opensearch-net
  opensearch-dashboards-cl2:
    image: opensearchproject/opensearch-dashboards:2.6.0
    container_name: opensearch-dashboards-cl2
    ports:
      - 5602:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-cl2-node1:9200","https://opensearch-cl2-node2:9200","https://opensearch-cl2-node3:9200"]'
    networks:
      - opensearch-net

volumes:
  search-eng-week4-cl1-d1:
  search-eng-week4-cl1-d2:
  search-eng-week4-cl1-d3:
  search-eng-week4-cl2-d1:
  search-eng-week4-cl2-d2:
  search-eng-week4-cl2-d3:
  search-eng-week4-cl1-snapshots:
  search-eng-week4-cl2-snapshots:


# explicitly set name, otherwise the docker network name is prepended with the folder (project) name
networks:
  opensearch-net:
    name: opensearch-net